# Generated by Django 5.2.3 on 2025-06-24 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auth',
            name='updateAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
