# Generated by Django 5.2.3 on 2025-06-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_auth_createdat_auth_updateat'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='user.user'),
        ),
    ]
