# Generated by Django 5.2.3 on 2025-06-24 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0002_auth_createdat_auth_updateat'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industryType', models.CharField(choices=[('TECH', 'Technology'), ('FIN', 'Finance'), ('EDU', 'Education'), ('HEALTH', 'Healthcare'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('profilePic', models.URLField(blank=True, default=None, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('flagCount', models.PositiveIntegerField(default=0)),
                ('isBanned', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updateAt', models.DateTimeField(auto_now=True)),
                ('bannedAt', models.DateTimeField(auto_now=True)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='_auth.auth')),
            ],
        ),
    ]
